
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.CoSoScalarFieldEnum = {
  id: 'id',
  ten: 'ten',
  diaChi: 'diaChi',
  trangThai: 'trangThai',
  sheetId: 'sheetId',
  bhxhUser: 'bhxhUser',
  bhxhPass: 'bhxhPass',
  bhxhMaCSKCB: 'bhxhMaCSKCB',
  bhxhHoTenCB: 'bhxhHoTenCB',
  bhxhCccdCB: 'bhxhCccdCB',
  hisHost: 'hisHost',
  hisPort: 'hisPort',
  hisUser: 'hisUser',
  hisPass: 'hisPass',
  hisDbName: 'hisDbName'
};

exports.Prisma.NguoiDungCSRScalarFieldEnum = {
  maNV: 'maNV',
  hoTen: 'hoTen',
  vaiTro: 'vaiTro',
  coSoId: 'coSoId',
  tenDangNhap: 'tenDangNhap',
  matKhauHash: 'matKhauHash',
  trangThai: 'trangThai'
};

exports.Prisma.BuoiKhamScalarFieldEnum = {
  id: 'id',
  coSoId: 'coSoId',
  ngayKham: 'ngayKham',
  xa: 'xa',
  diaDiem: 'diaDiem',
  ghiChu: 'ghiChu',
  nguoiTao: 'nguoiTao',
  createdAt: 'createdAt',
  syncStatus: 'syncStatus'
};

exports.Prisma.HoSoBenhNhanScalarFieldEnum = {
  id: 'id',
  maBN: 'maBN',
  maBNHIS: 'maBNHIS',
  stt: 'stt',
  buoiKhamId: 'buoiKhamId',
  coSoId: 'coSoId',
  hoTen: 'hoTen',
  gioiTinh: 'gioiTinh',
  ngaySinh: 'ngaySinh',
  namSinh: 'namSinh',
  cccd: 'cccd',
  diaChi: 'diaChi',
  sdt: 'sdt',
  sdtNguoiNha: 'sdtNguoiNha',
  thiLucMP: 'thiLucMP',
  thiLucMT: 'thiLucMT',
  chanDoan: 'chanDoan',
  chanDoanKhac: 'chanDoanKhac',
  khuyenNghi: 'khuyenNghi',
  bhyt: 'bhyt',
  tuVanVienMa: 'tuVanVienMa',
  soTienBao: 'soTienBao',
  ngayDieuTri: 'ngayDieuTri',
  diemDon: 'diemDon',
  gioDon: 'gioDon',
  nhom: 'nhom',
  followUpStatus: 'followUpStatus',
  nguoiPhuTrachMa: 'nguoiPhuTrachMa',
  nguoiChotCuoiMa: 'nguoiChotCuoiMa',
  ngayChot: 'ngayChot',
  daDon: 'daDon',
  ngayMoThucTe: 'ngayMoThucTe',
  soTienThucThu: 'soTienThucThu',
  trangThaiDieuTri: 'trangThaiDieuTri',
  ngayTaiKham: 'ngayTaiKham',
  ghiChuMat2: 'ghiChuMat2',
  trangThai: 'trangThai',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  syncStatus: 'syncStatus'
};

exports.Prisma.NhatKyTheoDoiScalarFieldEnum = {
  id: 'id',
  hoSoId: 'hoSoId',
  ngay: 'ngay',
  nguoiGoiMa: 'nguoiGoiMa',
  noiDung: 'noiDung',
  syncStatus: 'syncStatus'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  bang: 'bang',
  banGhiId: 'banGhiId',
  hanhDong: 'hanhDong',
  nguoiDung: 'nguoiDung',
  thoiDiem: 'thoiDiem',
  thayDoi: 'thayDoi'
};

exports.Prisma.SyncQueueScalarFieldEnum = {
  id: 'id',
  hoSoId: 'hoSoId',
  createdAt: 'createdAt',
  retries: 'retries'
};

exports.Prisma.DanhMucBenhVienScalarFieldEnum = {
  id: 'id',
  ten: 'ten',
  trangThai: 'trangThai'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  CoSo: 'CoSo',
  NguoiDungCSR: 'NguoiDungCSR',
  BuoiKham: 'BuoiKham',
  HoSoBenhNhan: 'HoSoBenhNhan',
  NhatKyTheoDoi: 'NhatKyTheoDoi',
  AuditLog: 'AuditLog',
  SyncQueue: 'SyncQueue',
  DanhMucBenhVien: 'DanhMucBenhVien'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
